### ISSUE TITLE
bulej93 - untrusted forwarders can create commitments

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#117]
bulej93

medium

# untrusted forwarders can create commitments

## Summary
anyone who isn't an approved market forwarder can create a commitment
## Vulnerability Detail
for anyone to be a lender they have to be a trusted market forwarder. however this can be bypassed through creating a commitment. there is no check whatsoever that the lender is a trusted market forwarder, so anyone basically can be a lender for any market
## Impact
anyone can be a lender for any market without having to be a trusted forwarder.
## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L177-L201
## Tool used

Manual Review

**Comment by bulej93** [comment]
Escalate for 10 USDC

for you to be a lender you need to be trusted by the protocol, but what if you could bypass that and create commitments however you want and in any market.

this is what `commitment` does, it creates commitments for lenders. it doesn't check whether the user is a trusted forwarder it not. anyone can creates a commitment in any market

**Comment by Trumpero** [comment]
It is obviously invalid. The entity that requires trust from the market is the marketForwarder contract, not the lender. The lender can create commitments within any marketForwarder contract, and the marketForwarder contract will be verified if it is trusted.
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L32-L45

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
As pointed out by the Lead judge `marketForwarder` is checked whether it is trusted.
