### ISSUE TITLE
ck - ERC721 tokens can be permanently lost if recipient is a contract that doesn't implement `onERC721Received`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#139]
ck

medium

# ERC721 tokens can be permanently lost if recipient is a contract that doesn't implement `onERC721Received`

## Summary

ERC721 tokens can be permanently lost if recipient is a contract that doesn't implement `onERC721Received`

## Vulnerability Detail

In the function `CollateralEscrowV1::_withdrawCollateral`, if the recipient of the ERC721 token is a contract that doesn't implement `onERC721Received`, the token would be permanently lost.

This is because `transferFrom` does not check whether a target contract is able to receive an ERC721 token. 

```solidity
        // Withdraw ERC721
        else if (_collateral._collateralType == CollateralType.ERC721) {
            require(_amount == 1, "Incorrect withdrawal amount");
            IERC721Upgradeable(_collateralAddress).transferFrom(
                address(this),
                _recipient,
                _collateral._tokenId
            );
        }
```

There are also no additional checks in the contract to ensure that the recipient is an EOA instead of a contract.
 
## Impact

Loss of ERC721 tokens.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L171-L179

## Tool used

Manual Review

## Recommendation

Either enforce restrictions that the recipient address of ERC721 tokens is an EOA. Alternativerly use the safeTransferFrom function.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is not valid M. _recipient is specified by the caller. According to Sherlock's consistent rules, it is not a valid M/H if one's own mistakes cause one's own losses.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

This should be considered invalid. 

There is not the possibility of a loss of tokens as the protocol is currently implemented. When a bid is accepted the `collateralManager` uses `transferFrom` to move the collateral into the escrow. 

https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L343-L347

This means that in order for the collateral to even be accepted into the escrow the borrower has shown the ability to issue approvals. 

Therefore the protocol can reliably transfer ERC721s to the borrower without using the "safe" method that calls `onERC721Received`, knowing that the borrower has already proven the ability to handle such tokens.

**Comment by ethereumdegen** [comment]
Github PR: [Issue 139 - Allow for specifying the recipient of a withdraw](https://github.com/teller-protocol/teller-protocol-v2/pull/80)

**Comment by hrishibhat** [comment]
Escalation accepted

Invalid issue
Agree with the comments in the 2nd escalation.
