### ISSUE TITLE
HexHackers - Borrower's Loan can unexpectedly default as there's no check for alignment between `_duration` and `_paymentDefaultDuration`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#185]
HexHackers

medium

# Borrower's Loan can unexpectedly default as there's no check for alignment between `_duration` and `_paymentDefaultDuration`

## Summary
Borrower's Loan can unexpectedly default as there's no check if  `_duration` <= `_paymentDefaultDuration`

## Vulnerability Detail
For example `_paymentDefaultDuration` can be set by market Owner to 10 days
but a borrower makes the recurring payment to be 14 days by setting `_duration` to 14 days and he'll think he's okay to make the payment in 14 days but instead the loan will automatically default.
## Impact
Borrower's Loan can default unexpectedly because there's no check to make sure the `_duration` set by the borrowers  is <= the `_paymentDefaultDuration` set by the market owners.

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L334-L411

## Tool used

Manual Review

## Recommendation
This can be prevented with a require statement in `_submitBid` like this:
```solidity
require(_duration <= _paymentDefaultDuration, "duration is above default payment date");
```

**Comment by cducrest** [comment]
Escalate for 10 USDC

I don't understand how this issue is considered valid. `_duration` in the provided code snippet is the total duration of the loan. It is expected to be longer than `_paymentDefaultDuration` in many cases and does not cause any problem. Issue does not explain a correct vulnerability or provide code snippets allowing to understand the flaw.

**Comment by ethereumdegen** [comment]
Github PR : [Issue 494 - improving logic for is loan liquidateable](https://github.com/teller-protocol/teller-protocol-v2/pull/91)

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
This issue is a user input error where the borrower can incorrectly set a longer _duration that _paymentDefaultDuration of the market he is submitting the bid for.
