### ISSUE TITLE
Inspex - Use `safeTransfer()` instead of `transfer()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#220]
Inspex

high

# Use `safeTransfer()` instead of `transfer()`

## Summary
The `transfer()` function of the `IERC20Upgradeable` interface return a boolean value that indicates a success status. However, some tokens do not implement the EIP20 standard correctly, and the `transfer()` function return void instead.

## Vulnerability Detail
After the lender accepts the borrower's bid, the borrower's collateral is deposited into the `CollateralEscrowV1` contract using the `SafeERC20Upgradeable.safeTransferFrom()` function.

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L119-L124

However, when users withdraw funds from the `CollateralEscrowV1` contract, such as when liquidating or fully repaying a loan, the token is transferred using the `IERC20Upgradeable.transfer()` function. This can cause issues with tokens that are not implemented according to the EIP20 standard, such as `USDT` token on the mainnet network, as they may be reverted.

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L166-L169

Therefore, if users use tokens that are not implemented according to the EIP20 standard, such as the `USDT` token, it can prevent the loan from being repaid or liquidated, potentially resulting in the loss of the user's collateral.

## Impact
Users of the Teller platform may be at risk of losing their collateral if they use non-EIP20 standard tokens such as the `USDT` token, which results in the token being reverted. This can cause the loan to become unrecoverable and result in the loss of the user's collateral.

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L166-L169

## Tool used

Manual Review

## Recommendation
We recommend adding the implementation of the OpenZeppelin's `SafeERC20` library, which replaces the usage of the `transfer()` function with the `safeTransfer()` function.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This should be valid low/info.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

This should be considered invalid.

There is not the possibility of a loss of tokens as the protocol is currently implemented. When a bid is accepted the collateralManager uses transferFrom to move the collateral into the escrow.

https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L327-L331

This means that in order for the collateral to even be accepted into the escrow, it has successfully been transferred without using the "safe" version. Non-standard tokens that would revert on transfer would never be able to be transferred into the escrow, and therefore they cannot become locked in the contract.

**Comment by cducrest** [comment]
> Escalate for 10 USDC
> 
> This issue should be considered invalid.
> 
> There is not the possibility of a loss of tokens as the protocol is currently implemented. When a bid is accepted, the collateralManager uses transferFrom to move the collateral into the escrow.
> 
> https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L327-L331
> 
> This means that in order for the collateral to even be accepted into the escrow, it has successfully been transferred without using the "safe" version. Non-standard tokens that would revert on transfer would never be able to be transferred into the escrow, and therefore they cannot become locked in the contract.

So you agree that a loan could be opened with no collateral at stake? That is already a loss of funds to the lender as the lender is not incentivized to repay their loans since there is no collateral. Meaning this is a valid issue (I thought it was high, based on the impact stated in https://github.com/sherlock-audit/2023-03-teller-judging/issues/343).

**Comment by dugdaniels** [comment]
> So you agree that a loan could be opened with no collateral at stake? That is already a loss of funds to the lender as the lender is not incentivized to repay their loans since there is no collateral. Meaning this is a valid issue (I thought it was high, based on the impact stated in https://github.com/sherlock-audit/2023-03-teller-judging/issues/343).

No, as the protocol is currently, it will not accept a token such as USDT as collateral. When it attempts to transfer the collateral into the escrow, it will revert, meaning the loan does not successfully happen. There is no possibly of a loss of funds.

**Comment by ethereumdegen** [comment]
Github PR: [Issue 220 - Use SafeTransfer in CollateralManager](https://github.com/teller-protocol/teller-protocol-v2/pull/77)

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Given that there is no loss of funds here, only being unable to use some tokens, this can be considered a low issue.
