### ISSUE TITLE
ctf_sec - Malicious borrower can block loan repayment on onERC1155Received ERC1155 safeTransferFrom hook and force lender to pay higher interest and even leads to liquidation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#225]
ctf_sec

high

# Malicious borrower can block loan repayment on onERC1155Received ERC1155 safeTransferFrom hook and force lender to pay higher interest and even leads to liquidation

## Summary

Malicious borrower can block loan repayment and force them to pay higher interest and even leads to liquidation

## Vulnerability Detail

Lender can repay the loan by calling TellerV2.sol repay function

```solidity
function _repayLoan(
	uint256 _bidId,
	Payment memory _payment,
	uint256 _owedAmount,
	bool _shouldWithdrawCollateral
) internal virtual {
	Bid storage bid = bids[_bidId];
	uint256 paymentAmount = _payment.principal + _payment.interest;

	RepMark mark = reputationManager.updateAccountReputation(
		bid.borrower,
		_bidId
	);

	// Check if we are sending a payment or amount remaining
	if (paymentAmount >= _owedAmount) {
		paymentAmount = _owedAmount;
		bid.state = BidState.PAID;

		// Remove borrower's active bid
		_borrowerBidsActive[bid.borrower].remove(_bidId);

		// If loan is is being liquidated and backed by collateral, withdraw and send to borrower
		if (_shouldWithdrawCollateral) {
			collateralManager.withdraw(_bidId);
		}

		emit LoanRepaid(_bidId);
	} else {
		emit LoanRepayment(_bidId);
	}
```

However, the borrower can refuse the payment if the underlying token is ERC1155

when the code above calling

```solidity
	if (_shouldWithdrawCollateral) {
		collateralManager.withdraw(_bidId);
	}
```

calling

```solidity
function withdraw(uint256 _bidId) external {
	BidState bidState = tellerV2.getBidState(_bidId);
	if (bidState == BidState.PAID) {
		_withdraw(_bidId, tellerV2.getLoanBorrower(_bidId));
	} else if (tellerV2.isLoanDefaulted(_bidId)) {
		_withdraw(_bidId, tellerV2.getLoanLender(_bidId));
		emit CollateralClaimed(_bidId);
	} else {
		revert("collateral cannot be withdrawn");
	}
}
```

calling

```solidity
    function _withdraw(uint256 _bidId, address _receiver) internal virtual {
        for (
            uint256 i;
            i < _bidCollaterals[_bidId].collateralAddresses.length();
            i++
        ) {
            // Get collateral info
            Collateral storage collateralInfo = _bidCollaterals[_bidId]
                .collateralInfo[
                    _bidCollaterals[_bidId].collateralAddresses.at(i)
                ];
            // Withdraw collateral from escrow and send it to bid lender
            ICollateralEscrowV1(_escrows[_bidId]).withdraw(
                collateralInfo._collateralAddress,
                collateralInfo._amount,
                _receiver
            );
            emit CollateralWithdrawn(
                _bidId,
                collateralInfo._collateralType,
                collateralInfo._collateralAddress,
                collateralInfo._amount,
                collateralInfo._tokenId,
                _receiver
            );
        }
    }
```

note the function call

```solidity
ICollateralEscrowV1(_escrows[_bidId]).withdraw(
	collateralInfo._collateralAddress,
	collateralInfo._amount,
	_receiver
);
```

we are calling

```solidity
    function _withdrawCollateral(
        Collateral memory _collateral,
        address _collateralAddress,
        uint256 _amount,
        address _recipient
    ) internal {
        // Withdraw ERC20
        if (_collateral._collateralType == CollateralType.ERC20) {
            IERC20Upgradeable(_collateralAddress).transfer(
                _recipient,
                _collateral._amount
            );
        }
        // Withdraw ERC721
        else if (_collateral._collateralType == CollateralType.ERC721) {
            require(_amount == 1, "Incorrect withdrawal amount");
            IERC721Upgradeable(_collateralAddress).transferFrom(
                address(this),
                _recipient,
                _collateral._tokenId
            );
        }
        // Withdraw ERC1155
        else if (_collateral._collateralType == CollateralType.ERC1155) {
            bytes memory data;

            IERC1155Upgradeable(_collateralAddress).safeTransferFrom(
                address(this),
                _recipient,
                _collateral._tokenId,
                _amount,
                data
            );
        } else {
            revert("Invalid collateral type");
        }
    }
```

if the collateral is ERC1155 token, we are calling

```solidity
IERC1155Upgradeable(_collateralAddress).safeTransferFrom(
	address(this),
	_recipient,
	_collateral._tokenId,
	_amount,
	data
);
```

the recipient is borrower.

when calling safeTransactionFrom to recipient address

the callback onERC1155 received is triggered.

According to https://eips.ethereum.org/EIPS/eip-1155

> ERC-1155 Token Receiver
Smart contracts MUST implement all of the functions in the ERC1155TokenReceiver interface to accept transfers. See “Safe Transfer Rules” for further detail.

> Smart contracts MUST implement the ERC-165 supportsInterface function and signify support for the ERC1155TokenReceiver interface to accept transfers. See “ERC1155TokenReceiver ERC-165 rules” for further detail.

a malicious borrower can implement function onERC1155 to conditionally block the loan repayment

```solidity
    function onERC1155Received(address _operator, address _from, uint256 _id, uint256 _value, bytes calldata _data) external returns(bytes4) {
	    if(happy) {
					return bytes4(keccak256("onERC1155Received(address,address,uint256,uint256,bytes)"))
		  } else {
		     revert("lender is rugged")
		  }
	}
```

this means that when the loan payment is blocked because the onERC1155Received hook revert, the lender is forced to burden the higher interest as time goes and interest accures and the debt can evetually bring the loan to liquidation and the borrower can seize the collateral of the lender at no cost.

## Impact

Lender is forced to pay higher interest because he cannot repay the loan and even being forced to liquidation while borrower pays no cost.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L736

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L253

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L184

## Tool used

Manual Review

## Recommendation

We recommend the protocol do not use ERC1155 safeTransferFrom to trigger the onERC1155Received hook.

**Comment by ethereumdegen** [comment]
Github PR: [Issue 225 - Separate logic for repay and collateral withdraw](https://github.com/teller-protocol/teller-protocol-v2/pull/69)

**Comment by ethereumdegen** [comment]
Alternative Github PR : https://github.com/teller-protocol/teller-protocol-v2/pull/104
