### ISSUE TITLE
shaka - Users cannot approve forwarder for a specific market

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#237]
shaka

medium

# Users cannot approve forwarder for a specific market

## Summary

Users cannot approve forwarder for a specific market.

## Vulnerability Detail

`TellerV2Context.sol:approveMarketForwarder` is supposed to approve a forwarder for a specific market, as we can read in the NatSpec of the function.

```solidity
81:     /**
82:      * @notice Approves a forwarder contract to use their address as a sender for a specific market.
83:      * @notice The forwarder given must be trusted by the market given.
84:      * @param _marketId An ID for a lending market.
85:      * @param _forwarder A forwarder contract address.
86:      */
87:     function approveMarketForwarder(uint256 _marketId, address _forwarder)
88:         external
89:     {
90:         require(
91:             isTrustedMarketForwarder(_marketId, _forwarder),
92:             "Forwarder must be trusted by the market"
93:         );
94:         _approvedForwarderSenders[_forwarder].add(_msgSender());
95:         emit MarketForwarderApproved(_marketId, _forwarder, _msgSender());
96:     }
```

However, the `_approvedForwarderSenders` stores only the address of the forwarder and the address of the sender, without storing the `_marketId`.

## Impact

The forwarder will obtain approval for all markets where it is trusted, even if the user just wanted to trust it for a specific market.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L81-L96

## Tool used

Manual Review

## Recommendation

Change the `_approvedForwarderSenders` mapping to store also market id.

```solidity
    // forwarder => market ID => set of pre-approved senders
    mapping(address => mapping(address => EnumerableSet.AddressSet)) 
        internal _approvedForwarderSenders;
```

**Comment by shaka0x** [comment]
Escalate for 10 USDC

The sponsor has disputed the issue saying that `There is not intention to approve a forwarder for a specific market at this time`. 

But this is obviously not the case. As we can read in the NatSpec of `approveMarketForwarder`
> @notice Approves a forwarder contract to use their address as a sender **for a specific market**.

![](https://i.imgur.com/iAcEKv4.png)

and the NatSpec of `hasApprovedMarketForwarder`
> @notice Checks if an account has approved a forwarder **for a market**.


What is more, in the case of not having the intention of approving a forwarder for a specific market, the `approveMarketForwarder` would not require to receive `_marketId` as a parameter.

**Comment by Trumpero** [comment]
I believe this issue is a low/info, as it is about an inconsistency in the NatSpec docs and does not result in any loss.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
This is an inconsistency in the natspec which does not cause loss of funds as pointed out by the Lead judge.
