### ISSUE TITLE
RaymondFam - Inadequate measures to prevent bad debts

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#247]
RaymondFam

medium

# Inadequate measures to prevent bad debts

## Summary
Collateral can only be claimed by the lender when the loan has defaulted or the loan liquidated 24 hours later regardless of how deep the loan has gone under water, culminating in losses to the lenders when market turns really bad. 

## Vulnerability Detail
Here is a typical scenario:

WETH market price = USD 2_000

1. Bob accepts a loan bid where 15_000 USDC is transferred to the borrower who has committed with a deposit of 10 WETH where the next payment due is 7 days from now.
2. Just one day later, the market starts going downhill where WETH price has quickly reached USD 1_500 the same day.
3. Bob tries to break even the deal at this point but has no option given other than to keep waiting till [`isLoanDefaulted()`](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L924-L931) return `true`.  
4. WETH price keeps fluctuating and by the time Bob is allowed to call [`CollateralManager.withdraw()`](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L250-L260), the 10 WETH claimed is only worth USD 10_000.

## Impact
Bob suffered a loss of USD 5_000, where the situation could have been worse had the loan entailed a longer payment cycle and a bigger principal amidst the market down trend.

The borrower could not be cared less repaying the debt since the 5_000 USDC could now be exchanged/swapped elsewhere for 15 WETH if need be.

Additionally, the market dip scenario will impact bullet loan the most since at any point throughout the loan duration the owed amount is always the entire principal lent.

## Code Snippet
[File: TellerV2.sol#L924-L931](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L924-L931)

```solidity
    function isLoanDefaulted(uint256 _bidId)
        public
        view
        override
        returns (bool)
    {
        return _canLiquidateLoan(_bidId, 0);
    }
```
[File: TellerV2.sol#L953-L969](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L953-L969)

```solidity
    function _canLiquidateLoan(uint256 _bidId, uint32 _liquidationDelay)
        internal
        view
        returns (bool)
    {
        Bid storage bid = bids[_bidId];

        // Make sure loan cannot be liquidated if it is not active
        if (bid.state != BidState.ACCEPTED) return false;

        if (bidDefaultDuration[_bidId] == 0) return false;

        return (uint32(block.timestamp) -
            _liquidationDelay -
            lastRepaidTimestamp(_bidId) >
            bidDefaultDuration[_bidId]);
    }
```
[File: CollateralManager.sol#L250-L260](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L250-L260)

```solidity
    function withdraw(uint256 _bidId) external {
        BidState bidState = tellerV2.getBidState(_bidId);
        if (bidState == BidState.PAID) {
            _withdraw(_bidId, tellerV2.getLoanBorrower(_bidId));
        } else if (tellerV2.isLoanDefaulted(_bidId)) {
            _withdraw(_bidId, tellerV2.getLoanLender(_bidId));
            emit CollateralClaimed(_bidId);
        } else {
            revert("collateral cannot be withdrawn");
        }
    }
```

## Tool used

Manual Review

## Recommendation
Consider implementing collateral factor to the loan committed such that `isLoanDefaulted()` can be optionally dependent on it to prevent a loan position from turning too unhealthy.

**Comment by raymondfam** [comment]
Escalate for 10 USDC
It is vividly evidenced in the codebase that the lenders would be helpless in the event of a drastic market downturn. This issue was described in detail, with a plausible real-world scenario and relevant code snippets provided for clarity. I also suggested a potential mitigation strategy involving the implementation of a collateral factor.

Note: `5_000 USDC` in the second paragraph of `Impact` should be corrected to `15_000 USDC` though.

**Comment by Trumpero** [comment]
This protocol is about time-based lending and doesn't depend on price, and users need to accept the risks of price. There are no references to price, value, oracles, etc., in the contracts. Therefore, I believe the scenario of price collapse is invalid or out of scope.

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
Given the protocol design, as pointed out by the Lead judge this issue can be considered out of scope.
