### ISSUE TITLE
ravikiran.web3 - LenderCommitmentForwarder.updateCommitmentBorrowers()

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#26]
ravikiran.web3

medium

# LenderCommitmentForwarder.updateCommitmentBorrowers()

## Summary
The implementation of updateCommitmentBorrowers function could lead to corrupt storage. In the commitment, the structure is maintaining a list of borrowersList, which is essentially an **EnumerableSetUpgradeable.AddressSet** mapped to the commitment id.

The problem is in the delete call on commitmentBorrowersList. The delete call can cause the storage to be corrupted and become unusable.

**Refer to the below documentation from OpenZeppelin**, [refer line 31 to 31 in the link]

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/structs/EnumerableSetUpgradeable.sol

## Vulnerability Detail
The way the list of borrowers for the commitment is done can corrupt the data.

## Impact
The list may become unreadable and conflict with the flow of the contract logic. The attempt to add element after deletion may fail.

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L240-L246

function updateCommitmentBorrowers(
        uint256 _commitmentId,
        address[] calldata _borrowerAddressList
    ) public commitmentLender(_commitmentId) {
        **delete commitmentBorrowersList[_commitmentId];**
        _addBorrowersToCommitmentAllowlist(_commitmentId, _borrowerAddressList);
    }

## Tool used

Manual Review
Code review done manually.

## Recommendation
Remove each element one by one using the remove function provided by the library. Or create a fresh instance of the array of EnumerableSet.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is not duplicate with issue #88. It describes the impact differently: **The list may become unreadable and conflict with the flow of the contract logic**. This is the wrong description. So this is valid Low/Info.

**Comment by pauliax** [comment]
Escalate for 10 USDC
If the comment says it is a duplicate of #88, then why both issues are open? But I agree with @securitygrid, here Watson failed to identify the real problem that it causes and wrote only an abstract description of a generic widely known issue.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
This issue does not describe the issue correctly as #88.

**Comment by ethereumdegen** [comment]
Github PR: [Issue 88 - Changing the way borrowers are updated for Lender Commitment](https://github.com/teller-protocol/teller-protocol-v2/pull/90)
