### ISSUE TITLE
ck - `claimLoanNFT` can be abused by a lender to maliciously reclaim a loan after transfering ownership

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#314]
ck

high

# `claimLoanNFT` can be abused by a lender to maliciously reclaim a loan after transfering ownership

## Summary

`claimLoanNFT` can be abused by a lender to maliciously reclaim a loan after transfering ownership

## Vulnerability Detail

When a lender is claiming a loan NFT, they get minted a new NFT even if they had already minted one.

```solidity
    function claimLoanNFT(uint256 _bidId)
        external
        acceptedLoan(_bidId, "claimLoanNFT")
        whenNotPaused
    {
        // Retrieve bid
        Bid storage bid = bids[_bidId];

        address sender = _msgSenderForMarket(bid.marketplaceId);
        require(sender == bid.lender, "only lender can claim NFT");
        // mint an NFT with the lender manager
        lenderManager.registerLoan(_bidId, sender);
        // set lender address to the lender manager so we know to check the owner of the NFT for the true lender
        bid.lender = address(lenderManager);
    }
```

Since the NFT represents ownership of a loan and can be transfered, a malicious owner could claim the NFT, transfer ownership, then mint another NFT reclaiming ownership.

Note that `require(sender == bid.lender, "only lender can claim NFT");` will always be true for the malicious lender.

Now when the loan gets repaid, the malicious lender would still get the repayment instead of the user they transfered the loan to.

```solidity
        address lender = getLoanLender(_bidId);

        // Send payment to the lender
        bid.loanDetails.lendingToken.safeTransferFrom(
            _msgSenderForMarket(bid.marketplaceId),
            lender,
            paymentAmount
        );
```

## Impact

Loss of funds for a user who got a loan transfered to them.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L560-L574

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L744-L751

## Tool used

Manual Review

## Recommendation

If an NFT has already being claimed for a `_bidId`, prevent the lender from claiming again for the same `_bidId`.

**Comment by iamckn** [comment]
Escalate for 10 USDC

This is a valid issue that shouldn't have been excluded.

**Comment by Trumpero** [comment]
I believe it is obviously invalid. After calling `claimLoanNft`, the lender cannot recall this function again because `bid.lender` has been changed to `address(lenderManager)`. Furthermore, `lenderManager` is an ERC721 contract and cannot mint an existing token ID.

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
Agree with the Lead judge's comment. the lender cannot reclaim or mint again.
