### ISSUE TITLE
immeas - due date and defaulting doesn't align

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#325]
immeas

medium

# due date and defaulting doesn't align

## Summary
`isPaymentLate` and `isLoanDefaulted/Liquidateable` doesn't align. A loan can be liquidatable without being late.

## Vulnerability Detail
Imagine a 360 day loan, with a 30 day payment cycle. The market has a 45 day default period

On Day 10 the borrower repays the first installment of the loan.

Jump forward 46 days.

`isPaymentLate` will say `false`. Since next due date is day 60.

`isLoanLiquidateable` will say `true` though. Since it's >(45+1) days since last payment.

## Impact
A borrower can be on track with payments (according to due dates and cycles) and still be defaulted/liquidated.

`isPaymentLate` might fool a borrower into a false sense of security. The loans doesn't actually work on a payment cycle basis rather you need to do at least a minimum payment within `bidDefaultDuration`.

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L854-L908

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L953-L969

## Tool used
Manual Review

## Recommendation
Two ways here. The easy one is remove the due date logic since that's not how the code for the repayments work. Or redo the repayment logic to work more in line with the due dates.

Duplicate of #78

**Comment by 0ximmeas** [comment]
Escalate for 10 USDC

Not a duplicate of https://github.com/sherlock-audit/2023-03-teller-judging/issues/503
Rather a duplicate of valid medium https://github.com/sherlock-audit/2023-03-teller-judging/issues/78

Both address the inconsistency between liquidation calculculation and due date calculation

**Comment by Trumpero** [comment]
I agree with the escalation that this issue should be a dup of #78. Additionally, I think both of them are similar with #185

**Comment by asendz** [comment]
> I agree with the escalation that this issue should be a dup of #78.

Your initial pre-edited comment said:
"I agree with the escalation that this issue should be a dup of #78.Additionally, I think both of them are similar with #185" 

What made you exclude #185? How is it that that 185 is different to this issue when the impact is the same and the fix is the same? Even their titles are the same? 

Also, the sponsors commented on 185 that they'll fix it so it's obviously valid but it is excluded now and this is valid? 

How does this work? @Trumpero @hrishibhat

**Comment by Trumpero** [comment]
@asendz After discussing with @hrishibhat  about the severity of this issue, we agreed that the scenario of this issue should be considered user's mistake when the borrower sets the loan duration too short and below defaultDuration. Furthermore, there are no other situations related to this issue that would result in medium severity.

**Comment by Trumpero** [comment]
@asendz Issue 325 highlights a problem with calculateNextDueDate function, which is different from the issue addressed in issue 185 involving _duration variable. The due date is also influenced by the bidPaymentCycleType (e.g., monthly, seconds, etc.), not just the duration of bid which set by the borrower. Therefore, I believe that issue 185 should be treated separately from issue 325. Furthermore, as we have not yet completed the resolution of escalations, this issue still requires a review from @hrishibhat  to determine its severity

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #78
