### ISSUE TITLE
spyrosonic10 - Use SafeERC20 for ERC20 and safeTransferFrom for ERC721

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#327]
spyrosonic10

medium

# Use SafeERC20 for ERC20 and safeTransferFrom for ERC721

## Summary
There are multiple instances where contract is not using safeTransfer, safeTransferFrom and safeApprove

## Vulnerability Detail
Usage of ERC721.transferFrom is discouraged as per OpenZeppelin.
ERC20 approve, transfer and transferFrom may fail as some token are not compatible with IERC20 interface. 

## Impact
Token transfer/approve will fail and hence disrupt contract functionality

## Code Snippet

Usage of ERC20.transferFrom
[CollateralManager.sol#L327](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L327)

Usage of ERC20.transfer
[CollateralEscrowV1.sol#L166](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L166)

Usage of ERC20.approve
[CollateralManager.sol#L332](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L332)

Usage of ERC721.transferFrom
[CollateralManager.sol#L343](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L343)
[CollateralEscrowV1.sol#L129](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L129)
[CollateralEscrowV1.sol#L174](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L174)

## Tool used

Manual Review

## Recommendation

Consider using SafeERC20 for ERC20 tokens and safeTransferFrom for ERC721 tokens

Duplicate of #220

**Comment by bulej93** [comment]
Escalate for 10 USDC

this and all its duplicates are valid lows. the contract will still perform its functions and there will be no damage at all. if its a valid medium then let that be communicated and put in writing in the Sherlock docs

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
