### ISSUE TITLE
yixxas - Rebasing token deposited into escrow cannot be withdrawn

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#345]
yixxas

high

# Rebasing token deposited into escrow cannot be withdrawn

## Summary
This vulnerability happens because of 2 different issues in the contract. 

1. `depositAsset()` does not take into account rebasing token despite protocol wanting to support them. 
2. Wrong implementation in `_withdrawCollateral()`

## Vulnerability Detail
In `_withdrawCollateral()`, if collateral being withdrawn is ERC20, it uses the parameter `_collateral._amount` instead of `_amount`. This means that when withdrawing ERC20 tokens, we are forced to withdraw all collaterals deposited as parameter `_amount` is unused.

Next, the flaw in `depositAsset()` is that rebasing tokens can rebase up or down periodically. The value saved in `collateral._amount`  can wrong as the actual balance in the contract can change. If token rebases down, `balanceOf(tokenId) < collateral._amount`.

By combining this 2 issues, the first bug forces owner to withdraw all collateral. But the 2nd bug prevents this withdrawal as amount reflected in `collateral._amount` is less than what the contract actually holds should the token rebases down, hence will revert, preventing owner from withdrawing the token.

## Impact
Asset will not be withdrawable.

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L158-L170
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L51-L76

## Tool used

Manual Review

## Recommendation
`_collateral._amount` is not reliable if token used is rebasing token. Consider taking the balance of contract instead.

We should also fix `_withdrawCollateral()` to allow owner to withdraw arbitrary amount of token.

```diff
        if (_collateral._collateralType == CollateralType.ERC20) {
            IERC20Upgradeable(_collateralAddress).transfer(
                _recipient,
-                _collateral._amount
+               _amount
            );  
        }   
```

Duplicate of #140

**Comment by yixxas** [comment]
Escalate for 10 USDC

This issue is not the same as #140 and should be deduped. The main issue #140 and its duplicates only identifies the second issue, where `_amount` is not used due to the wrong implementation. This by itself only means that there is a limitation on what users can withdraw, that they cannot do partial withdrawal.  

Combining this issue with the fact that rebasing tokens can rebase downwards collaterals used cannot actually be withdrew once it is deposited. It breaks the protocol assumptions as it wants to support all ERC20 tokens as indicated by the docs.

> During the audit, please verify that rebasing ERC20 tokens and other weird tokens will not interfere with the protocol assumptions. If a rebasing/weird token breaks just the loan that it is in, we want to know about it but that is bad but largely OK (not hyper critical) since the borrower and lender both agreed to that asset manually beforehand

Based on what the protocol expects above, this clearly breaks the protocol assumption. It is also wrong for the protocol to say that it is OK for users to lose ALL their deposited collateral by depositing a rebasing token, considering that the protocol SUPPORTS them.

**Comment by pauliax** [comment]
Escalate for 10 USDC.
If it is deduped then it should be invalid because from scope: "REBASING TOKENS: none (not supported)".
However, seems that this issue is also touching #140, so Watson should be happy with the initial judgment then.

**Comment by Trumpero** [comment]
This issue has 2 root causes: incorrect `collateral._amount` (similar to #140) and the use of a rebasing token (which is considered invalid as the contest docs labels it as NOT SUPPORTED). Therefore, this issue should be a duplicate of #140, even if the assumption of a rebasing token is invalid. I believe the escalation from Yixxas should be rejected, while the escalation from Pauliax should be accepted.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Maintaining duplicate of #140 
But not a medium on its own. Agreed that the protocol comment could be open the interpretation but considering this a low based on two things:
> REBASING TOKENS: none (not supported)
> the borrower and lender both agreed to that asset manually beforehand
