### ISSUE TITLE
cducrest-brainbot - TellerV2 calculateNextDueDate may leave no time for user to repay loan

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#379]
cducrest-brainbot

medium

# TellerV2 calculateNextDueDate may leave no time for user to repay loan

## Summary

The function `calculateNextDueDate` might give a due date too early when loan reaches end of duration resulting in a bad reputation update for borrower.

This behaviour does not match the behaviour deciding whether a position is liquidateable.

## Vulnerability Detail

In TellerV2, the function `calculateNextDueDate` calculates the next due date for loans using the payment cycle type, duration, loan accepted time, and last repay time. At the end of the calculation, if the due date is past the end of loan date it sets the due date to end of loan:
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L854-L908

```solidity
        uint32 endOfLoan = bid.loanDetails.acceptedTimestamp +
            bid.loanDetails.loanDuration;
        //if we are in the last payment cycle, the next due date is the end of loan duration
        if (dueDate_ > endOfLoan) {
            dueDate_ = endOfLoan;
        }
```

It can be for example that a loan lasts for 100 seconds and is to be repaid every 9 seconds. If at second 99 the borrower repays the loan, the next due date according to the function will be at second 100. This gives the borrower only 1 second until his payment is considered late (there might not even be a block minted at second 100).

The function `calculateNextDueDate()` is used to determine if a payment is late:

```solidity
    function isPaymentLate(uint256 _bidId) public view override returns (bool) {
        if (bids[_bidId].state != BidState.ACCEPTED) return false;
        return uint32(block.timestamp) > calculateNextDueDate(_bidId);
    }
```

## Impact

The function `isPaymentLate()` is used in the (out of scope) contract to mark a loan as `Delinquant` when payment is late:
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/ReputationManager.sol#L94-L113

This function can be called by anyone through the public function `updateAccountReputation`.

I did not investigate further how bad the impact is to the system as this contract is out of scope and believe the impact to be medium.

## Tool used

Manual Review

## Recommendation

Only consider loan payment late when it is past end of loan time + some margin based on the cycle payment length. Alternatively, consider the payment late only when liquidateable by the lender.

**Comment by cducrest** [comment]
Escalate for 10 USDC

I don't understand what makes https://github.com/sherlock-audit/2023-03-teller-judging/issues/78 valid medium and not this one.
Both issues point to discrepancy in between `calculateNextDueDate` and `isPaymentLate`, whether you decide which of the two functions is correct seem arbitrary to me.

**Comment by Trumpero** [comment]
I respectfully disagree with the escalation. This issue is distinct from #78, since issue #78 specifically highlights the scenario where the liquidation delay time is shorter than the repayment period, putting the borrowers' collateral at risk of being liquidated. Additionally, this issue does not result in any loss of funds, but only affects the `updateAccountReputation` function which is out of scope, during a special short period (1 second in the scenario of the report). So I believe it should be a low/info issue.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
As pointed out by the Lead judge this affects only an out-of-scope contract.
