### ISSUE TITLE
monrel - Forwarders can not be revoked. Lenders are perpetually exposed to approved forwarders.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#390]
monrel

medium

# Forwarders can not be revoked. Lenders are perpetually exposed to approved forwarders.

## Summary

MarketForwarders can never be revoked this is a risk to lenders since a compromised forwarder can drain all funds approved for any market. This can be done even if they have no committed loans on the compromised market.

## Vulnerability Detail

Lenders have a responsibility to assess if a market owner is trustworthy and to vet if a market forwarder is safe to use.

The issue comes from the fact that a compromised forwarder could steal all funds that a lender has approved on ANY market even if the lender has "exited" that market by not committing any loans there. 

A forwarder that has once been approved will always pass the required check on [L115-119](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L115-L119) used in `lenderAcceptBid()`

```solidity
require(
	_approvedForwarderSenders[_msgSender()].contains(sender),
	"Sender must approve market forwarder"
)
```

which means that a forwarder will always be able to successfully call  `lenderAcceptBid()` on behalf of the lender.

 An upgradable forwarder if compromised could call `lenderAcceptBid()` on TellerV2 and accept any bid and transfer all of the funds that a lender has approved for ALL other markets. See [L535-539](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L535-L539)

```solidity
bid.loanDetails.lendingToken.safeTransferFrom(
	sender,
	bid.receiver,
	amountToBorrower
);
```

Example scenario:

1. Lender Bob approves MarketA and ForwarderA. ForwarderA is an upgradable contract.
2. Lender Bob decides to not use MarketA anymore and therefore commits no loans. It is reasonable for Bob to assume that he is not in any way exposed to MarketA or ForwarderA.
3. Bob continues to issue loans on other markets.
4. After 1 year ForwarderA is compromised. The contract is upgraded and can make arbitrary calls to TellerV2.
5. ForwarderA creates bids with 0 collateral on MarketA and accepts those bids on behalf of Bob by calling `lenderAcceptBid()`. All of Bob's assets approved for other markets can now be drained.

## Impact

Since there is no way to revoke market forwarders lenders are perpetually exposed to risks of any forwarder that they have ever approved even if they are not active on those markets.

If any forwarder is ever exposed that they have used AFTER they have left those markets all of their funds approved for other markets can be drained.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L115-L119

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L535-L539

## Tool used

Manual Review

## Recommendation
Lenders should be able to revoke forwarders. By doing so they can completely exit a market and have no exposure to forwarders in markets they have left.

Add this function to TellerV2Context.

```solidity
    function revokeMarketForwarder(uint256 _marketId, address _forwarder)
        external
    {
        _approvedForwarderSenders[_forwarder].remove(msg.sender);
        emit MarketForwarderRevoked(_marketId, _forwarder, msg.sender;
	}
```

Duplicate of #433

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Considering this issue a low as the market forwarder is trusted as mentioned in the code and the readme. A compromised forwarder would have the same impact as the compromise of any other trusted role in a protocol which Sherlock considers low/informational.
