### ISSUE TITLE
cducrest-brainbot - Loans are liquidateable even when honest if bidDefaultDuration < paymentCycle

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#400]
cducrest-brainbot

medium

# Loans are liquidateable even when honest if bidDefaultDuration < paymentCycle

## Summary

The calculation to determine if a loan is liquidateable does not take into account the payment cycle duration. Under certain circumstances where the payment cycle is shorter than the bid default duration, an honest borrower may repay its loan correctly every cycle but end up being defaulted and liquidated by the lender.

## Vulnerability Detail

The function to determined if a loan is defaulted checks if the last payment was done more than `bidDefaultDuration[_bidId]` seconds ago:

```solidity
    function isLoanDefaulted(uint256 _bidId)
        public
        view
        override
        returns (bool)
    {
        return _canLiquidateLoan(_bidId, 0);
    }
...
    function _canLiquidateLoan(uint256 _bidId, uint32 _liquidationDelay)
        internal
        view
        returns (bool)
    {
        Bid storage bid = bids[_bidId];

        // Make sure loan cannot be liquidated if it is not active
        if (bid.state != BidState.ACCEPTED) return false;

        if (bidDefaultDuration[_bidId] == 0) return false;

        return (uint32(block.timestamp) -
            _liquidationDelay -
            lastRepaidTimestamp(_bidId) >
            bidDefaultDuration[_bidId]);
    }
```

The value for `bidDefaultDuration` is set during the bid submission and is taken from the `marketRegistry`:
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L376

This value is controlled by the owner of the market:
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/MarketRegistry.sol#L487-L511

## Impact

An honest user doing its repayment every cycle may be considered defaulted if the market parameters allow it. This could be done by a mischievous market owner but also as a mistake. This will result in a borrower loan being defaulted and the borrower losing its collateral to the lender (or in the worst case to a liquidator) while the borrower honestly attempted to repay its loan.

I expected values for the payment cycle to be close to a week and default duration close to a month, however by checking the live contracts on mainnet in the MarketRegistry for `marketId = 3` I see: `paymentCycle = PaymentDefaultDuration = 2592000 (720 hours)`. I see similar values for other market id.

https://etherscan.io/address/0x5e30357d5136Bc4BfaDBA1ab341D0da09Fe7a9F1#readProxyContract

## Tool used

Manual Review

## Recommendation

Consider a loan as defaulted only when the last payment has been made `PaymentDefaultDuration` after it was due. Otherwise make sure market owners cannot set `PaymentDefaultDuration` below `paymentCycle`.

Duplicate of #92

**Comment by cducrest** [comment]
Escalate for 10 USDC

Not a duplicate of https://github.com/sherlock-audit/2023-03-teller-judging/issues/503
Rather a duplicate of valid medium https://github.com/sherlock-audit/2023-03-teller-judging/issues/92

Both this issue and 92 point to a problem when default duration is lower than payment cycle stating the lender can liquidate the loan without the borrower having the chance / having the need to repay its loan. Both issues also point out the fact that this parameter is controlled by market owner which could abuse it to immediately take and liquidate a loan.

**Comment by Trumpero** [comment]
Agree with the escalation.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #92
