### ISSUE TITLE
tsvetanovv - If `onlyTellerV2` is not the `owner` function `depositAsset()` will fail

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#418]
tsvetanovv

high

# If `onlyTellerV2` is not the `owner` function `depositAsset()` will fail

## Summary
In `CollateralManager.sol` we have [deployAndDeposit()](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L179-L199) function.

```soldiity
function deployAndDeposit(uint256 _bidId) external onlyTellerV2 {
        if (isBidCollateralBacked(_bidId)) {
            (address proxyAddress, ) = _deployEscrow(_bidId);
            _escrows[_bidId] = proxyAddress;

            for (
                uint256 i;
                i < _bidCollaterals[_bidId].collateralAddresses.length();
                i++
            ) {
                _deposit(
                    _bidId,
                    _bidCollaterals[_bidId].collateralInfo[
                        _bidCollaterals[_bidId].collateralAddresses.at(i)
                    ]
                );
            }

            emit CollateralEscrowDeployed(_bidId, proxyAddress);
        }
    }
```
This function deploys a new collateral escrow and deposits collateral.

`deployAndDeposit()` call [deposit()](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L316-L386) function. This function deploys a new collateral escrow contract. Deposits collateral into a collateral escrow.

Note in particular that this function calls [depositAsset()](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L51-L76) in several places:
```solidity
336: collateralEscrow.depositAsset(
352: collateralEscrow.depositAsset(
370: collateralEscrow.depositAsset(
```
The problem comes when `depositAsset()` is called.

## Vulnerability Detail

Because `deployAndDeposit` has `onlyTellerV2` modifier: 
```solidity
/* Modifiers */
    modifier onlyTellerV2() {
        require(_msgSender() == address(tellerV2), "Sender not authorized");
        _;
    }
```
And `depositAsset()` function has `onlyOnwer` modifier.
```solidity
function depositAsset(
        CollateralType _collateralType,
        address _collateralAddress,
        uint256 _amount,
        uint256 _tokenId
    ) external payable virtual onlyOwner {
```

It is possible that `tellerV2` is not the owner. Then the `depositAsset()` function cannot be executed.

## Impact

If `onlyTellerV2` is not the `owner` function `depositAsset()` will fail.

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L179-L199
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L316-L386
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L51-L76

## Tool used

Manual Review

## Recommendation

Instead of `onlyOnwer` modifier in `depositAsset()` function a require statement can be added to check the `msg.sender` == `owner `or `msg.sender == address(tellerV2)`.

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

I think this is a valid issue. I don't know why it's `Excluded` without any explanation.

**Comment by pauliax** [comment]
> Escalate for 10 USDC
> 
> I think this is a valid issue. I don't know why it's `Excluded` without any explanation.

Escrow initialize sets the right owner:
```solidity
    function _deployEscrow(uint256 _bidId)
        internal
        virtual
        returns (address proxyAddress_, address borrower_)
    {
        proxyAddress_ = _escrows[_bidId];
        // Get bid info
        borrower_ = tellerV2.getLoanBorrower(_bidId);
        if (proxyAddress_ == address(0)) {
            require(borrower_ != address(0), "Bid does not exist");

            BeaconProxy proxy = new BeaconProxy(
                collateralEscrowBeacon,
                abi.encodeWithSelector(
                    ICollateralEscrowV1.initialize.selector,
                    _bidId
                )
            );
            proxyAddress_ = address(proxy);
        }
    }
```

```solidity
    function initialize(uint256 _bidId) public initializer {
        __Ownable_init();
        bidId = _bidId;
    }
```
