### ISSUE TITLE
GimelSec - Users cannot renounce approval to the market forwarder

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#433]
GimelSec

high

# Users cannot renounce approval to the market forwarder

## Summary

ERC2771 has a security concern that the forwarder can forge the value of `_msgSender()`. And in TellerV2, the `TellerV2Contex.approveMarketForwarder` can help mitigate such issue. However, users can only approve the forwarder. They cannot remove the approvals. 

## Vulnerability Detail

`TellerV2Contex.approveMarketForwarder`  lets users approve the market forwarder. And the forwarder can only use their addresses if they approved the forwarder first.
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L87
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L116
```solidity
    function approveMarketForwarder(uint256 _marketId, address _forwarder)
        external
    {
        require(
            isTrustedMarketForwarder(_marketId, _forwarder),
            "Forwarder must be trusted by the market"
        );
        _approvedForwarderSenders[_forwarder].add(_msgSender());
        emit MarketForwarderApproved(_marketId, _forwarder, _msgSender());
    }

    function _msgSenderForMarket(uint256 _marketId)
        internal
        view
        virtual
        returns (address)
    {
        if (isTrustedMarketForwarder(_marketId, _msgSender())) {
            address sender;
            assembly {
                sender := shr(96, calldataload(sub(calldatasize(), 20)))
            }
            // Ensure the appended sender address approved the forwarder
            require(
                _approvedForwarderSenders[_msgSender()].contains(sender),
                "Sender must approve market forwarder"
            );
            return sender;
        }

        return _msgSender();
    }
```

However, there is no method to cancel the approval. The forwarder can always use the address of the user once the user has approved the forwarder.   

## Impact

A user may want to leave TellerV2 without any concern. So the approval should be able to be removed even if the forwarder is trusted.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L87
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L116

## Tool used

Manual Review

## Recommendation

Add a function to remove the approval. And use mapping instead of array to make removal easier.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
According to Sherlock's rules, This is not valid M. So far, it hasn't produced bad results.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

This should be considered Low/Informational. Sherlock judging criteria requires a valid report for a Medium to illustrate a scenario where a material amount of funds can be lost. This report does not meet that requirement.

**Comment by ethereumdegen** [comment]
Github PR : [Issue 443 - Allow for renouncing market forwarder](https://github.com/teller-protocol/teller-protocol-v2/pull/87)

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Considering the issue and its duplicates as low as the market forwarder is trusted as mentioned in the code and the readme.    A compromised forwarder would have the same impact as the compromise of any other trusted role in a protocol which sherlock considers low/informational.
