### ISSUE TITLE
J4de - `LenderCommitmentForwarder.sol ` `CommitmentAllowlist` can only be added but not deleted

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#73]
J4de

medium

# `LenderCommitmentForwarder.sol ` `CommitmentAllowlist` can only be added but not deleted

## Summary

`LenderCommitmentForwarder.sol ` `CommitmentAllowlist` can only be added but not deleted.

## Vulnerability Detail

```solidity
File: LenderCommitmentForwarder.sol
243     function updateCommitmentBorrowers(
244         uint256 _commitmentId,
245         address[] calldata _borrowerAddressList
246     ) public commitmentLender(_commitmentId) {
247         delete commitmentBorrowersList[_commitmentId];
248         _addBorrowersToCommitmentAllowlist(_commitmentId, _borrowerAddressList);
249     }
```

Lenders can issue a loan order through the `LenderCommitmentForwarder.sol` contract, and if the borrower is satisfied with the order, they can accept it to complete the loan. Unlike `TellerV2.sol` contract, this contract market is dominated by lenders, and lenders can choose to lend their orders only to borrowers in the whitelist.

Lenders can call `updateCommitmentBorrowers` function to add whitelist borrowers. The problem here is that the whitelist can only be added but not deleted, which leads to the fact that if a lender finds that a borrower no longer meets the requirements, he cannot be removed from the list.

## Impact

Lenders' loans may be borrowed by untrustworthy borrowers.

## Code Snippet

https://github.com/teller-protocol/teller-protocol-v2/blob/cb66c9e348cdf1fd6d9b0416a49d663f5b6a693c/packages/contracts/contracts/LenderCommitmentForwarder.sol#L240-L246

## Tool used

Manual Review

## Recommendation

It is recommended to add an function to delete whitelist borrowers.

**Comment by 0xmonrel** [comment]
Escalate for 10 USDC

This is an invalid issue and is not a duplicate of #433. The way you change the whitelist is by calling the same function with a separate list of addresses.

There is a separate issue that makes it impossible to delete from the whitelist due to memory corruption seen in #88 but that is not what this issue is about.

**Comment by Trumpero** [comment]
Agree with the escalation. This is a distinct issue, and it should be considered invalid because the `commitmentBorrowersList` will be deleted when the lender calls `updateCommitmentBorrowers`.

**Comment by hrishibhat** [comment]
Escalation accepted

Invalid issue
Not a duplicate of #433 
As pointed out in the escalation the changing of whitelist is done by calling the same function with a new list of addresses
