### ISSUE TITLE
Bauer - Use safeMint instead of mint for ERC721

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#8]
Bauer

medium

# Use safeMint instead of mint for ERC721

## Summary
Use safeMint instead of mint for ERC721
## Vulnerability Detail
The msg.sender will be minted as a proof of staking NFT when  the `claimLoanNFT()` function is called.
However, if lender is a contract address that does not support ERC721, the NFT can be frozen in the contract.

As per the documentation of EIP-721:
A wallet/broker/auction application MUST implement the wallet interface if it will accept safe transfers.

Ref: https://eips.ethereum.org/EIPS/eip-721
As per the documentation of ERC721.sol by Openzeppelin
Ref: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L274-L285
```solidity
LenderManager.sol
   function registerLoan(uint256 _bidId, address _newLender)
        public
        override
        onlyOwner
    {
        _mint(_newLender, _bidId);
    }

```
## Impact
Users possibly lose their NFTs

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderManager.sol#L45

## Tool used

Manual Review

## Recommendation
Use safeMint instead of mint to check received address support for ERC721 implementation.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L262

**Comment by ethereumdegen** [comment]
Github PR: [Issue 8 - Use SafeMint](https://github.com/teller-protocol/teller-protocol-v2/pull/79)

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Users unable to claim/mint ERC721 if they do not have the necessary implementations if the protocol design clearly expects users to be able to is a valid low issue. Also as pointed out, safeMint can always add more issues to the code. 
The same will be updated in Sherlock rules.
