### ISSUE TITLE
deadrxsezzz - Lenders might suffer losses if the ERC20 in the loan has fee on transfer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#94]
deadrxsezzz

medium

# Lenders might suffer losses if the ERC20 in the loan has fee on transfer

## Summary
Lenders will receive less interest than expected and might even lose value 

## Vulnerability Detail
When repaying a loan, it only checks the amount sent, but not the amount received. The two values might differ if the ERC20 has implemented fee-on-transfer. Furthermore, a lender cannot simply increase the fees beforehand to compensate for these losses, as in the case where the token has a flat fee/ flat fee + %, the lender will suffer significantly more losses if the borrower repays the loan over numerous repayments

## Impact
Lenders will receive less interest than expected and might even lose value

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L747-#L751

## Tool used
Manual Review

## Recommendation
Implement logic to check the amount received by the lender to insure that no losses for them have occurred. 

Duplicate of #91

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
Disagree with duplication. #91 states that the contract is incompatible with Fee-on-Transfer tokens. 
#94 (my issue) describes that the lender might suffer extra losses in a certain scenario, when fee-on-transfer tokens are used, well described above.
Project states that it should be compatible with fee-on-transfer tokens in the contest FAQ: 
> FEE-ON-TRANSFER: any

Would love to hear judge's opinion on this one.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid duplicate of #91 
There can be different issues arising out of using the same underlying issue of using Fee-on-transfer tokens. 
Maintaining the state
